name: notebooks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "shap/**"
      - "notebooks/**"
      - ".github/workflows/run_notebooks.yml"
      - "scripts/**"
      - "pyproject.toml"
      - "setup.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel only PR intermediate builds
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  run_notebooks:
    runs-on: "ubuntu-latest"
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use "eager" update strategy in case cached dependencies are outdated
          # Using regular install NOT editable install: see GH #3020
          pip install --upgrade --upgrade-strategy eager '.[test,plots,test_notebooks]'
      - name: Run notebooks
        run: |
          python scripts/run_notebooks_timeouts.py
